#!/bin/bash

SERVICE=acromere

CLIENT_SOURCE=/opt/acm/repo/latest/www.acromere.com/client.zip
CLIENT_TARGET=/opt/acm/web/www.acromere.com/client
CLIENT_LATEST=$(ls -t $CLIENT_SOURCE)

echo "Deploying client: $CLIENT_LATEST"
echo "              To: $CLIENT_TARGET/$SERVICE.zip"

mkdir -p "$CLIENT_TARGET"
cp $CLIENT_LATEST $CLIENT_TARGET/$SERVICE.zip && unzip -o -d $CLIENT_TARGET $CLIENT_TARGET/$SERVICE.zip
